version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: DEVELOPMENT
  reviewers:
  - bucky-boy
  - MrBurtyyy
  assignees:
  - MrBurtyyy
