language: java

cache:
  directories:
    $HOME/.m2

env:
  - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

git:
  depth: 3

jobs:
  include:
    - state: Test
      jdk: oraclejdk8
      install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -Ddependency-check.skip=true
      script:
        - ./mvnw test -B -Ddependency-check.skip=true
    - &test-compatability
      stage: Compatability
      jdk: oraclejdk8
      os: linux
      install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -Ddependency-check.skip=true
      script:
        - ./mvnw test -B -Ddependency-check.skip=true
    - <<: *test-compatability
      # Only the api and implementation need testing with Java 1.7
      dist: precise
      jdk: oraclejdk7
      install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
      script:
        - ./mvnw test -B -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
    - <<: *test-compatability
      dist: precise
      jdk: openjdk7
      install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
      script:
        - ./mvnw test -B -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
    - <<: *test-compatability
      jdk: openjdk8
    - <<: *test-compatability
      jdk: oraclejdk9
    - <<: *test-compatability
      jdk: openjdk9
    - <<: *test-compatability
      dist: bionic
      jdk: openjdk10
